version: "3.8"

services:
  cockroachdb:
    image: cockroachdb/cockroach:v23.1.11
    command: start-single-node --insecure
    volumes:
      - cockroach-data:/cockroach/cockroach-data
    ports:
      - "26257:26257"
      - "8080:8080"

  nakama:
    image: heroiclabs/nakama:3.20.0
    entrypoint:
      - "/bin/sh"
      - "-ecx"
      - >
        echo "Waiting 10s for CockroachDB to start..." &&
        sleep 10 &&
        /nakama/nakama migrate up --database.address root@cockroachdb:26257 &&
        exec /nakama/nakama
        --name nakama1
        --database.address root@cockroachdb:26257
        --logger.level DEBUG
        --session.token_expiry_sec 7200
        --runtime.path /backend/build
    volumes:
      - ./backend/build:/backend/build
    depends_on:
      - cockroachdb
    ports:
      - "7350:7350"
      - "7351:7351"

volumes:
  cockroach-data:
